#!/usr/bin/env php
<?php
defined('YII_DEBUG') or define('YII_DEBUG', true);
defined('YII_ENV') or define('YII_ENV', 'test');
defined('YII_APP_BASE_PATH') or define('YII_APP_BASE_PATH',dirname(__DIR__));
require(YII_APP_BASE_PATH . '/vendor/autoload.php');
$dotenv = new \Dotenv\Dotenv(__DIR__);
$dotenv->load();
require(YII_APP_BASE_PATH . '/vendor/yiisoft/yii2/Yii.php');
Yii::setAlias('@tests', __DIR__);
$config = \yii\helpers\ArrayHelper::merge(
    require(__DIR__ . '/config/base.php'),
    require(__DIR__ . '/config/console.php')
);
$app = new \yii\console\Application($config);
$code = $app->run();
exit($code);